version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@3.2.0
jobs:
  build:
    working_directory: ~/app
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run:
          name: Run local dynamo db
          command: docker run -p 8000:8000 amazon/dynamodb-local
      - run:
          name: Create Dynamodb table
          command: aws dynamodb create-table --table-name HelloWorldDynamoDB --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url http://localhost:8000
      - run: 
          name: Run sam local api
          command: sam local start-api
          background: true
      - run: sleep 1m

      - run:
          name: Install Node packages
          command: npm --prefix hello-world/ install --frozen-lockfile

      - run:
          name: "Run lambda test"
          command: npm --prefix hello-world/ run test
          no_output_timeout: "2m"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos