version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@3.2.0
jobs:
  build:
    working_directory: ~/app
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-lambda
      - run: sleep 1m

      - run: 
          name: Navigate to app directory
          command: cd hello-world 

      - run:
          name: Install Node packages
          command: npm install --frozen-lockfile

      - run:
          name: "Run lambda test"
          command: npm run test
          no_output_timeout: "2m"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos