version: 2
orbs:
  sam: circleci/aws-sam-serverless@3.2.0
jobs:
  build:
    docker:
      - image: cypress/base:18.6.0
    working_directory: 
      ~/app
    steps:
      - checkout
      - sam/install
      - run: 
          name: Start SAM instance
          command: sam local start-lambda
          background: true

      - run: sleep 1m

      - run: 
          name: Navigate to app directory
          command: cd hello-world 

      - run:
          name: Install Node packages
          command: npm install --frozen-lockfile

      - run:
          name: "Run lambda test"
          command: npm run test
          no_output_timeout: "2m"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos